services:
  - type: web
    name: tg-neurobot
    runtime: python
    env: python
    region: frankfurt  # или другой ближайший
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
