services:
  - type: web
    name: telegram-multibot
    env: python
    region: frankfurt # или ближайший к тебе
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9